### ISSUE TITLE
Была Пробная Лицензия 31.05.2019

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/Trassa#12]
17.05.2019 Запросили новую Лицензию «B» (там дата до 01.05.2019)
После того как получили Лицензию «B» выскочил Диалог с ошибкой (но ошибки не было, была получена лицензия «B» с истёкшим сроком…).
На самом деле Лицензия «B» была получена с Сервера (у этой лицензии истёкший срок действия просто) + отображается информация о том, что лицензия неактивирована.
	Но похоже что то ломается… При новом запросе в этой же сессии Приложения в ситуации когда Лицензия неактивирована при запросе Лицензии предлагается «пробный серийный номер», а не тот, который был получен с Сервера для «B».
Далее в этой же сессии Приложения в ситуации когда Лицензия неактивирована при запросе Лицензии (а там в этой запрашиваемой Лицензии 01.05.2019) выполняется Запрос к Серверу, Сервер выдаёт Лицензию, но выводится Диалог «Произошла ошибка во время активации. Попробуйте еще раз или отправьте отчёт об ошибке». То есть 
В ситуации когда Лицензия неактивирована (истёк срок действия Приложения) Приложение не

**Comment by ISPLab** [comment]
Также требуется проверить обновление лицензии при исправлении данной ошибки

**Comment by ISPLab** [comment]
вывел дополнительный вариант ошибки при активации в случае истекшей даты лицензии
убрал вариант с временной лицензией - надо перепроверить
