### ISSUE TITLE
На странице «Все протоколы»:

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/Trassa#33]
Если выбран Протокол, который содержит ddd-файл, то правила работы с этим Протоколом подобны этапу Проверки, а именно:
1)	Если в наборе активностей ddd-файла из Протокола есть данные, которые больше текущей даты + 1 день, то они не должны обрабатываться, они должны быть отфильтрованы без ошибки.
2)	Если среди оставшихся активностей есть хотя бы одна активность с датой, превышающей срок окончания лицензии, то нужно не открывать этот Протокол. В этом случае сразу после выбора такого Протокола пользователю должно быть выдано сообщение об ошибке «Ошибка: истёк срок действия лицензии».

**Comment by ISPLab** [comment]
1 в вопросе ключевая фраза - не должны обрабатываться. Обработка осуществляется а в п5анализаторе Мне дорабатывать его?
2 Вопрос, как может появиться протокол с данными превышающий срок окончания лицензии? (ответ исходя из первого вопроса)
