### ISSUE TITLE
страница Проверки. Если меняется одновременно и "фамилия" и "имя отчество", то в группе "Выявленные нарушения" чекбокс появляется только для фамилии, а чекбокс для "имени отчества" не появляется.

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/Trassa#35]
Доп. информация: если меняется только "имя отчество", то в группе "Выявленные нарушения" чекбокс для "имени отчества" появляется.

**Comment by ISPLab** [comment]
да так и есть, если фамилия не совпадает имя не проверяется
