### ISSUE TITLE
Нестыковка при оформлении Протокола

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/Trassa#36]
1. При проверке Международных рейсов, которые должны контролироваться по Закондательству ЕСТР, выявлено, что тахографа нет.
2. В Приложении к Протоколу фиксируется нарушение со ссылкой на 36-й Приказ РФ. Это неверно.
Требуется сделать следующее:
1. Про 36й Приказ в Приложении к Протоколу не писать ничего и никогда.
2. Если же всё-таки данные были считаны с карты и определены нарушения режима труда и отдыха, то в Приложении к Протоколу всегда указывать по какому Законодательству выполнялась эта проверка (по 15му Приказу РФ или по ЕСТР), причём независимо ни от каких настроек. Так как если сведения о Законодательстве, по которому проверялся режим труда и отдыха, не указаны в Приложении к Протоколу то непонятно по какому Законодательству оно анализировалось.
3. Настройку "Добавлять ссылки на Приказы и Постановления РФ" убрать - она лишняя и ненужная.

**Comment by ISPLab** [comment]
В случае если  ЕСТР писаться ссылки на 36 приказ  не будут
