### ISSUE TITLE
Нет возможности просмотра детализации проверки ЭЦП (ЕСТР ddd-файлы HIHOLA и SHYTSIK)

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/Trassa#38]

**Comment by ISPLab** [comment]
есть возможность
![image](https://user-images.githubusercontent.com/8803512/58364726-f3c36400-7ec0-11e9-8723-437d8d90df74.png)

![image](https://user-images.githubusercontent.com/8803512/58364742-3edd7700-7ec1-11e9-8fdd-048ede020449.png)
