### ISSUE TITLE
Не строится детализированный отчёт по деятельности и нарушениям режимов труда и отдыха водителя.

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/Trassa#39]
ЕСТР ddd-файлы HIHOLA и SHYTSIK.
В настройках:
2028 дней проверки режима труда и отдыха водителя
20 последних смен для детального просмотра.
Отображается список из 20-ти смен. При этом для каждой смены указывается С=01.01.0001 ПО=01.01.0001. Самих таблиц с активностями и прочей информацией для каждой смены НЕТ.

**Comment by ISPLab** [comment]
не указывается
![image](https://user-images.githubusercontent.com/8803512/58364678-ab0bab00-7ec0-11e9-8825-df5728358b8a.png)
