### ISSUE TITLE
Детализированный отчёт по деятельности и нарушениям режимов труда и отдыха водителя вызывает аварийное завершение программы.

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/Trassa#40]
ЕСТР ddd-файлы HIHOLA.
В настройках:
2028 дней проверки режима труда и отдыха водителя
365 последних смен для детального просмотра.

**Comment by ISPLab** [comment]
![image](https://user-images.githubusercontent.com/8803512/58364659-5cf6a780-7ec0-11e9-8960-587383de7bf8.png)
а если поставить 3000000 ?
